name: gerador_senhas
description: Um app Flutter para geração de senhas seguras.
publish_to: "none" # porque é só local

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Biblioteca de hashing
  crypto: ^3.0.6
  # Biblioteca de criptografia simétrica (AES, etc)
  encrypt: ^5.0.3
  # Para salvar preferências do usuário
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
